# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open In Order
email:
description: The Jekyll version of the Phantom theme by HTML5 UP.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://openinorder.to/" # the base hostname & protocol for your site
gems:
  - jekyll-redirect-from
# Social settings
github_username: sparcopen
twitter_username: sparc_na

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: false #true or false
front-page-posts: 12 #maximum number of posts to show on front page
